name = "RadiationPyrometers"
uuid = "f583effd-a810-4e6b-b1e2-2b4349a685d7"
authors = ["Roman Mironov"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
